# Generated by Django 5.0.1 on 2024-01-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0003_surveypoints_staging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveypoints_staging',
            name='radius',
            field=models.CharField(max_length=20),
        ),
    ]
