# Generated by Django 5.0.1 on 2024-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0004_alter_surveypoints_staging_radius'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyPoints_staging',
        ),
        migrations.AlterField(
            model_name='surveypoints',
            name='ipaddress',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveypoints',
            name='radius',
            field=models.CharField(max_length=20),
        ),
    ]
