# Generated by Django 5.0.1 on 2024-01-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0005_delete_surveypoints_staging_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyPoints',
            new_name='SurveyPoint',
        ),
    ]
