# Generated by Django 5.0.1 on 2024-01-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0006_rename_surveypoints_surveypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveypoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='surveypoint',
            name='cartodb_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
