# Generated by Django 5.0.1 on 2024-02-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0007_remove_surveypoint_id_alter_surveypoint_cartodb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveypoint',
            name='myid',
            field=models.IntegerField(null=True),
        ),
    ]
