# Generated by Django 5.0.1 on 2024-02-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0008_surveypoint_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveypoint',
            name='myid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
