# Generated by Django 5.0.1 on 2024-02-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0010_remove_surveypoint_myid_surveypoint_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveypoint',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
