# Generated by Django 5.0.1 on 2024-02-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0011_alter_surveypoint_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveypoint',
            name='cartodb_id',
        ),
        migrations.AddField(
            model_name='surveypoint',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
