# Generated by Django 5.1 on 2024-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSummary',
            fields=[
                ('responseid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ts_start', models.DateField()),
                ('ts_end', models.DateField()),
                ('duration', models.DurationField()),
                ('ipaddr', models.CharField(max_length=20)),
                ('recordct', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Response summaries',
                'db_table': 'response_summary',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
        migrations.AddField(
            model_name='surveypoint',
            name='surveyid',
            field=models.CharField(default='none'),
        ),
    ]
