# Generated by Django 5.1.6 on 2025-05-08 02:38

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0002_responsesummary_delete_worldborder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('geojson', djgeojson.fields.GeoJSONField()),
            ],
        ),
    ]
