# Generated by Django 5.1.6 on 2025-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0003_geojsonlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapconfig',
            name='layers',
            field=models.ManyToManyField(to='pio.geojsonlayer'),
        ),
    ]
