# Generated by Django 5.1.6 on 2025-05-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0004_mapconfig_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapconfig',
            name='layers',
            field=models.ManyToManyField(blank=True, to='pio.geojsonlayer'),
        ),
    ]
