# Generated by Django 5.2.1 on 2025-06-02 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0005_alter_mapconfig_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('geojson', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Feature Layers',
            },
        ),
        migrations.CreateModel(
            name='FeatureLayerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_order', models.IntegerField(help_text='Lower values render first (bottom)')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pio.featurelayer')),
                ('mapconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pio.mapconfig')),
            ],
            options={
                'ordering': ['z_order'],
                'unique_together': {('mapconfig', 'layer'), ('mapconfig', 'z_order')},
            },
        ),
        migrations.DeleteModel(
            name='GeoJSONLayer',
        ),

# stepwise version of above
        migrations.RemoveField(
            model_name='mapconfig',
            name='layers',
        ),
        migrations.AddField(
            model_name='mapconfig',
            name='layers',
            field=models.ManyToManyField(blank=True, related_name='mapconfig', through='pio.FeatureLayerOrder', to='pio.featurelayer'),
        ),
    ]
