# Generated by Django 5.2.1 on 2025-05-21 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0005_alter_mapconfig_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveypoint',
            name='mapconfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pio.mapconfig'),
        ),
    ]
