# Generated by Django 5.2.1 on 2025-06-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0006_featurelayer_featurelayerorder_delete_geojsonlayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelayerorder',
            name='z_order',
            field=models.IntegerField(default=1, help_text='Lower values render first (bottom)'),
        ),
    ]
