# Generated by Django 5.2.1 on 2025-06-13 00:56

import pio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0007_alter_featurelayerorder_z_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurelayerorder',
            name='config',
            field=models.JSONField(default=pio.models.maplayer_default),
        ),
    ]
