# Generated by Django 5.2.1 on 2025-06-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0008_featurelayerorder_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureLayerOrder',
            new_name='MapLayer',
        ),
    ]
