# Generated by Django 5.2.7 on 2025-10-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0006_surveypoint_mapconfig'),
        ('pio', '0009_rename_featurelayerorder_maplayer'),
    ]

    operations = [
    ]
