# Generated by Django 5.2.7 on 2025-10-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pio', '0011_basemap_mapbasemap_mapconfig_basemaps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemap',
            options={'verbose_name': 'Basemap', 'verbose_name_plural': 'Basemaps'},
        ),
        migrations.AlterModelOptions(
            name='featurelayer',
            options={'verbose_name': 'Feature layer', 'verbose_name_plural': 'Feature layers'},
        ),
        migrations.AlterModelOptions(
            name='mapconfig',
            options={'ordering': ['slug'], 'verbose_name': 'Map setup', 'verbose_name_plural': 'Map setups'},
        ),
        migrations.AlterField(
            model_name='mapbasemap',
            name='z_index',
            field=models.IntegerField(default=-10, help_text='Rendering order for basemaps (must be ≤ 0, lower values render first/bottom). Leave gaps between values (e.g., -10, -20, -30) for easier reordering.'),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='z_order',
            field=models.IntegerField(default=10, help_text='Rendering order for feature layers (positive values, higher renders on top). Leave gaps between values (e.g., 10, 20, 30) for easier reordering. Survey points render at z=1000.'),
        ),
    ]
